// The trip, in order. Edit this file to add or update details —
// nothing else needs to change.
const TRIP = {
  // Bump this whenever the itinerary content changes — shown at the top of the page.
  updated: '2026-08-15T08:00:13Z',

  // Trimmed to Sep 2–9 for now — full trip is Aug 28–Sep 16, see entries below.
  start: '2026-09-02',
  end: '2026-09-09',

  entries: [
    {
      id: 'leg-mnl-doh',
      type: 'leg',
      mode: 'flight',
      from: { code: 'MNL', city: 'Manila' },
      to: { code: 'DOH', city: 'Doha' },
      date: '2026-08-28',
      depart: '11:50 PM',
      arrive: '3:45 AM',
      arriveDate: '2026-08-29',
    },
    {
      id: 'leg-doh-zrh',
      type: 'leg',
      mode: 'flight',
      from: { code: 'DOH', city: 'Doha' },
      to: { code: 'ZRH', city: 'Zurich' },
      date: '2026-08-29',
      depart: '8:20 AM',
      arrive: '2:20 PM',
    },
    {
      id: 'stay-zurich',
      type: 'stay',
      city: 'Zurich',
      country: 'Switzerland',
      start: '2026-08-29',
      end: '2026-09-02',
      address: null,
    },
    {
      id: 'leg-zrh-paris',
      type: 'leg',
      mode: 'train',
      trainName: 'TGV Lyria',
      from: { code: 'ZRH', city: 'Zurich' },
      to: { code: 'PAR', city: 'Paris · Gare de Lyon' },
      date: '2026-09-02',
      depart: '11:34 AM',
      arrive: '3:55 PM',
    },
    {
      id: 'stay-paris',
      type: 'stay',
      city: 'Paris',
      country: 'France',
      start: '2026-09-02',
      end: '2026-09-09',
      address: '41 Rue de Verneuil',
      coords: [48.8583, 2.3277],
      wedding: {
        couple: 'Helen & Tristan',
        events: [
          {
            name: 'Opening Night',
            date: '2026-09-04',
            time: '7:00 PM',
            venue: 'Le Studio des Acacias',
            address: '17th Arrondissement, Paris',
            dress: "Smart casual — wear what you're comfortable in <strong>(just not a white dress)</strong>.",
            note: 'Cocktail party with hors d’oeuvres and small plates.',
          },
          {
            name: 'Ceremony',
            date: '2026-09-05',
            time: '5 – 6:30 PM',
            venue: 'Le Trianon',
            address: '80 Boulevard de Rochechouart, 75018 Paris',
            dress: 'Black tie recommended, formal evening attire. <strong>Any color but white.</strong>',
            note: 'Ceremony in the theatre, cocktail hour to follow in the lobby.',
          },
          {
            name: 'Dinner & Dancing',
            date: '2026-09-05',
            time: '6:30 – 11 PM',
            venue: 'L’Élysée Montmartre',
            address: '72 Boulevard de Rochechouart, 75018 Paris',
            dress: 'Same as ceremony — black tie recommended.',
            note: 'Seated dinner, toasts, and late-night dancing. Coat check for personal items and dance shoes.',
          },
        ],
      },
    },
    {
      id: 'leg-paris-avignon',
      type: 'leg',
      mode: 'train',
      trainName: 'TGV',
      from: { code: 'PAR', city: 'Paris · Gare de Lyon' },
      to: { code: 'AVI', city: 'Avignon' },
      date: '2026-09-09',
      depart: '12:38 PM',
      arrive: '3:15 PM',
    },
    {
      id: 'stay-gordes',
      type: 'stay',
      city: 'Gordes',
      country: 'France',
      start: '2026-09-09',
      end: '2026-09-12',
      address: null,
    },
    {
      id: 'leg-marseille-rome',
      type: 'leg',
      mode: 'flight',
      from: { code: 'MRS', city: 'Marseille' },
      to: { code: 'FCO', city: 'Rome · Fiumicino' },
      date: '2026-09-12',
      depart: '8:00 AM',
      arrive: '9:25 AM',
    },
    {
      id: 'stay-rome',
      type: 'stay',
      city: 'Rome',
      country: 'Italy',
      start: '2026-09-12',
      end: '2026-09-15',
      address: null,
    },
    {
      id: 'leg-fco-doh',
      type: 'leg',
      mode: 'flight',
      from: { code: 'FCO', city: 'Rome' },
      to: { code: 'DOH', city: 'Doha' },
      date: '2026-09-15',
      depart: '10:40 PM',
      arrive: '5:05 AM',
      arriveDate: '2026-09-16',
      flightNumber: 'QR 114',
      airline: 'Qatar Airways',
      aircraft: 'Airbus A350-900',
      baggage: 'Economy (O) · 25kg checked',
    },
    {
      id: 'leg-doh-mnl',
      type: 'leg',
      mode: 'flight',
      from: { code: 'DOH', city: 'Doha' },
      to: { code: 'MNL', city: 'Manila' },
      date: '2026-09-16',
      depart: '7:55 AM',
      arrive: '10:20 PM',
      flightNumber: 'QR 928',
      airline: 'Qatar Airways',
      aircraft: 'Boeing 777-300ER',
      baggage: 'Economy (O) · 25kg checked',
    },
  ],

  // Day-specific plans, keyed by date. Each date holds a list — a day can have more than one.
  days: {
    '2026-09-02': [
      {
        time: '3:55 PM',
        kind: 'transit',
        title: 'Travel to the Apartment',
        notes: 'Allow up to 80 minutes after the train for luggage, the transfer, and check-in, which may run later than 4:00 PM.',
      },
      {
        time: '5:15 PM',
        kind: 'activity',
        title: 'Explore Saint-Germain & Rue de Buci',
        notes: 'Short arrival-day stroll before the café — flexible if check-in runs long.',
      },
      {
        time: '6:00 PM',
        kind: 'meal',
        title: 'Café de Flore / Les Deux Magots',
        notes: 'Coffee break at a historic café on Bd Saint-Germain.',
      },
      {
        time: '6:40 PM',
        kind: 'meal',
        title: 'La Rhumerie / Maison Sauvage',
        notes: 'Aperitif on Rue de Buci — optional if dinner timing is tight.',
      },
      {
        time: '7:15 PM',
        kind: 'meal',
        title: 'Le Comptoir du Relais',
        notes: 'Arrival dinner, no reservation assumed — treat as a bonus, not a must. Alt: Le Bon Saint Pourcain, Bistro des Augustins, Semilla, Brasserie Lipp.',
      },
      {
        time: '9:15 PM',
        kind: 'meal',
        title: 'Pierre Hermé',
        notes: 'Macarons and pastries on Rue Bonaparte — optional.',
      },
    ],
    '2026-09-03': [
      {
        time: '8:40 AM',
        kind: 'transit',
        title: 'Travel to the Louvre',
        notes: 'Leave with a buffer to arrive ~9:15 AM, before the 9:30 AM timed entry.',
      },
      {
        time: '9:30 AM',
        kind: 'activity',
        title: 'The Louvre',
        notes: 'Locked reservation, 9:30 AM entry.',
        address: 'Musée du Louvre, 75001 Paris',
        coords: [48.8606, 2.3376],
      },
      {
        time: '12:00 PM',
        kind: 'activity',
        title: 'Tuileries Garden',
        notes: 'Walk directly from the Louvre — keep this short to protect the afternoon reservation sequence.',
        address: 'Jardin des Tuileries, 75001 Paris',
        coords: [48.8634, 2.3275],
      },
      {
        time: '12:45 PM',
        kind: 'activity',
        title: 'Rue Saint-Honoré',
        notes: 'Shopping — Maison Labiche, Sœur, A.P.C., Sandro, Maje. Prioritize 2–3 shops rather than trying to visit all.',
      },
      {
        time: '2:00 PM',
        kind: 'transit',
        title: 'Travel to Ralph’s Coffee',
        notes: 'Leave buffer for transit and walking — don’t extend shopping past 2:00 PM.',
      },
      {
        time: '3:00 PM',
        kind: 'meal',
        title: 'Ralph’s Coffee',
        notes: 'Locked reservation, 3:00 PM — aim to leave by 3:50–3:55 rather than stretching the stop.',
      },
      {
        time: '3:55 PM',
        kind: 'transit',
        title: 'Travel to the Eiffel Tower',
        notes: 'Tight transfer — the Eiffel visit takes priority over letting shopping/coffee run long.',
      },
      {
        time: '4:15 PM',
        kind: 'activity',
        title: 'Eiffel Tower',
        notes: 'Timed ticket — prioritize 2nd floor/summit as available, allow time for security.',
        address: 'Eiffel Tower, 5 Avenue Anatole France, 75007 Paris',
        coords: [48.8584, 2.2945],
      },
      {
        time: '6:15 PM',
        kind: 'transit',
        title: 'Travel to Dinner',
        notes: 'Taxi if traffic allows — protect the 7:00 PM reservation.',
      },
      {
        time: '7:00 PM',
        kind: 'meal',
        title: 'La Bourse et La Vie',
        notes: 'Locked reservation, 7:00 PM.',
        address: '12 Rue Vivienne, 75002 Paris',
        coords: [48.8695, 2.3403],
      },
      {
        time: '9:00 PM',
        kind: 'transit',
        title: 'Travel to Angelina',
        notes: 'Optional — only if dinner finishes on time.',
      },
      {
        time: '9:30 PM',
        kind: 'meal',
        title: 'Angelina',
        notes: 'Hot chocolate and dessert on Rue de Rivoli — optional if dinner runs long.',
      },
    ],
    '2026-09-04': [
      {
        time: '9:15 AM',
        kind: 'transit',
        title: 'Travel to Le Marais',
        notes: 'Leave the apartment with enough time to begin at 9:30 AM.',
      },
      {
        time: '9:30 AM',
        kind: 'activity',
        title: 'Place des Vosges & Hôtel de Sully',
        notes: 'Morning stroll through Le Marais.',
      },
      {
        time: '10:30 AM',
        kind: 'activity',
        title: 'Le Marais',
        notes: 'Shopping — Merci, Fleux, Papier Tigre, The Broken Arm. Walk between shops, prioritize favorites over seeing all four.',
      },
      {
        time: '11:30 AM',
        kind: 'meal',
        title: 'Fringe',
        notes: 'Quick specialty coffee before the noon Bouillon République reservation — keep this brief.',
      },
      {
        time: '12:00 PM',
        kind: 'meal',
        title: 'Bouillon République',
        notes: 'Locked reservation, 12:00 PM.',
      },
      {
        time: '1:45 PM',
        kind: 'transit',
        title: 'Travel to the Market',
        notes: 'Short transfer after lunch.',
      },
      {
        time: '2:00 PM',
        kind: 'activity',
        title: 'Marché des Enfants Rouges',
        notes: 'Post-lunch market visit — browse the food stalls, dessert or coffee if desired.',
      },
      {
        time: '3:00 PM',
        kind: 'transit',
        title: 'Travel to the Apartment',
        notes: 'Return promptly to protect the wedding preparation window.',
      },
      {
        time: '3:30 PM',
        kind: 'activity',
        title: 'Rest & Prep',
        notes: 'Unpack, shower, and start getting ready for the Wedding Opening Night — prioritize being fully dressed before leaving for the Arc de Triomphe.',
      },
      {
        time: '5:00 PM',
        kind: 'transit',
        title: 'Travel to the Arc de Triomphe',
        notes: 'Leave promptly — taxi minimizes transfer uncertainty.',
      },
      {
        time: '5:30 PM',
        kind: 'activity',
        title: 'Arc de Triomphe',
        notes: 'Short exterior/photo stop — skip the rooftop unless there’s ample time and the schedule allows.',
        address: 'Arc de Triomphe, Place Charles de Gaulle, 75008 Paris',
        coords: [48.8738, 2.295],
      },
      {
        time: '6:00 PM',
        kind: 'transit',
        title: 'Travel to the Wedding Venue',
        notes: 'Leave immediately after photos — allow a traffic buffer.',
      },
      {
        time: '6:30 PM',
        kind: 'activity',
        title: 'Arrive at the Venue',
        notes: 'Arrive early enough to find the entrance, check in, and settle before the 7:00 PM event.',
      },
    ],
    '2026-09-05': [
      {
        time: '8:40 AM',
        kind: 'transit',
        title: 'Leave the Apartment',
        notes: 'Walk/short metro toward the bakery stops — allow about 20 minutes.',
      },
      {
        time: '9:00 AM',
        kind: 'meal',
        title: 'Claire Damon / Terroirs d’Avenir',
        notes: 'Pick up baguette, butter, cheese, berries, and pastries — strictly 2 stops max, skip Maison Louvard if either runs long.',
      },
      {
        time: '10:00 AM',
        kind: 'transit',
        title: 'Travel to the Luxembourg Gardens',
        notes: 'Keep the transfer efficient so the picnic stays relaxed.',
      },
      {
        time: '10:15 AM',
        kind: 'activity',
        title: 'Jardin du Luxembourg',
        notes: 'Morning picnic with coffee from Coutume or Treize au Jardin — leave promptly for lunch.',
      },
      {
        time: '11:30 AM',
        kind: 'transit',
        title: 'Travel to Lunch',
        notes: 'Very short local transfer.',
      },
      {
        time: '11:40 AM',
        kind: 'meal',
        title: 'Le Bonaparte',
        notes: 'Sit-down lunch in Saint-Germain — earlier lunch gives more recovery time before the ceremony.',
      },
      {
        time: '1:00 PM',
        kind: 'transit',
        title: 'Travel to the Apartment',
        notes: 'Return promptly for the protected preparation window.',
      },
      {
        time: '1:15 PM',
        kind: 'activity',
        title: 'Rest & Prep',
        notes: 'Unwind, do hair/makeup, and suit up for the ceremony — protected prep window.',
      },
      {
        time: '3:45 PM',
        kind: 'transit',
        title: 'Travel to Le Trianon',
        notes: 'Leave early for traffic and an arrival buffer.',
      },
    ],
    '2026-09-06': [
      {
        time: '10:15 AM',
        kind: 'transit',
        title: 'Leave the Apartment',
        notes: 'Easy walk along the Seine — Musée d’Orsay is close, same arrondissement.',
      },
      {
        time: '10:30 AM',
        kind: 'activity',
        title: 'Musée d’Orsay',
        notes: 'Later start to allow recovery after the late wedding reception — shorten or skip if feeling tired.',
      },
      {
        time: '12:00 PM',
        kind: 'transit',
        title: 'Travel to Lunch',
        notes: 'Short transfer toward Saint-Germain.',
      },
      {
        time: '12:15 PM',
        kind: 'meal',
        title: 'Le Relais de l’Entrecôte',
        notes: 'Arrive around the lunch opening. Alt: Joséphine Chez Dumonet, Le Petit Lutetia, Café Varenne.',
      },
      {
        time: '1:30 PM',
        kind: 'transit',
        title: 'Travel to Le Bon Marché',
        notes: 'Easy transfer after lunch.',
      },
      {
        time: '2:00 PM',
        kind: 'activity',
        title: 'Le Bon Marché',
        notes: 'Shopping — Fleuron, A.P.C., Polène, Jérôme Dreyfuss. Keep this flexible, prioritize favorite shops.',
      },
      {
        time: '4:00 PM',
        kind: 'activity',
        title: 'La Grande Épicerie',
        notes: 'Gourmet souvenirs — Mariage Frères tea, Bordier butter, Alain Ducasse chocolate, Bonne Maman.',
      },
      {
        time: '5:30 PM',
        kind: 'meal',
        title: 'Café de La Grande Épicerie',
        notes: 'Afternoon coffee and tea — keep it local rather than crossing to the 1st.',
      },
      {
        time: '6:30 PM',
        kind: 'transit',
        title: 'Travel to Gare de Lyon',
        notes: 'Protected buffer before the 8:30 PM reservation.',
      },
      {
        time: '8:30 PM',
        kind: 'meal',
        title: 'Le Train Bleu',
        notes: 'Locked reservation, 8:30 PM, at Gare de Lyon.',
      },
    ],
    '2026-09-07': [
      {
        time: '9:40 AM',
        kind: 'transit',
        title: 'Leave the Apartment',
        notes: 'Walk toward the Seine and Pont Neuf — allow about 20 minutes.',
      },
      {
        time: '10:00 AM',
        kind: 'meal',
        title: 'Café Nuances',
        notes: 'Morning coffee — kept central to stay near the Seine.',
      },
      {
        time: '11:00 AM',
        kind: 'activity',
        title: 'Pont Neuf & Île Saint-Louis',
        notes: 'Leisurely stroll — no need to rush the islands.',
      },
      {
        time: '1:00 PM',
        kind: 'activity',
        title: 'Île Saint-Louis Stroll',
        notes: 'Berthillon is closed Mondays — substitute another ice cream stop or just extend the stroll.',
      },
      {
        time: '2:00 PM',
        kind: 'activity',
        title: 'Rue du Bac & Seine',
        notes: 'Gallery browsing and a Seine stroll — start heading west toward Trocadéro by 4:30 PM.',
      },
      {
        time: '4:30 PM',
        kind: 'transit',
        title: 'Travel to Trocadéro',
        notes: 'Leave enough time for a relaxed viewpoint visit before the cruise.',
      },
      {
        time: '5:00 PM',
        kind: 'activity',
        title: 'Trocadéro',
        notes: 'Eiffel Tower viewpoint and photos — best positioned here before the evening cruise.',
        address: 'Trocadéro, 75016 Paris',
        coords: [48.862, 2.2887],
      },
      {
        time: '5:45 PM',
        kind: 'transit',
        title: 'Travel to the Eiffel Tower',
        notes: 'Take the stairs/gardens route toward the Seine — allow time for photos.',
      },
      {
        time: '6:15 PM',
        kind: 'activity',
        title: 'Eiffel Tower & Seine',
        notes: 'Short pre-dinner stop — head toward dinner from here.',
      },
      {
        time: '6:30 PM',
        kind: 'meal',
        title: 'Dinner',
        notes: 'Location TBD — allow travel time to get there once it’s booked.',
      },
      {
        time: '7:45 PM',
        kind: 'transit',
        title: 'Travel to the Cruise Dock',
        notes: 'Arrive before boarding — keep this buffer rather than cutting it close.',
      },
      {
        time: '8:15 PM',
        kind: 'activity',
        title: 'Vedettes de Paris',
        notes: 'Evening Seine cruise, 8:15 PM — Champagne cruise booked.',
      },
    ],
    '2026-09-08': [
      {
        time: '8:45 AM',
        kind: 'transit',
        title: 'Leave the Apartment',
        notes: 'Montmartre is a real crossing from the 7th — metro with a transfer or a taxi, allow 40–45 minutes.',
      },
      {
        time: '9:30 AM',
        kind: 'activity',
        title: 'Montmartre & Sacré-Cœur',
        notes: 'Sacré-Cœur, Rue de l’Abreuvoir, Place Dalida.',
      },
      {
        time: '12:00 PM',
        kind: 'meal',
        title: 'KB Coffee Roasters / Le Consulat',
        notes: 'Coffee break in Montmartre — keep it light, save room for the market later.',
      },
      {
        time: '12:45 PM',
        kind: 'transit',
        title: 'Travel to Le Marais',
        notes: 'Head south toward the Marais — protect the market visit.',
      },
      {
        time: '1:30 PM',
        kind: 'activity',
        title: 'Marché des Enfants Rouges',
        notes: 'Flexible market stop — grab a small bite or browse the stalls.',
      },
      {
        time: '2:15 PM',
        kind: 'transit',
        title: 'Travel to Île de la Cité',
        notes: 'Allow time for the cross-river transfer.',
      },
      {
        time: '2:35 PM',
        kind: 'activity',
        title: 'Shakespeare and Company',
        notes: 'Browse the historic English-language bookshop — keep it to 30–40 minutes.',
        address: '37 Rue de la Bûcherie, 75005 Paris',
        coords: [48.8523, 2.3471],
      },
      {
        time: '3:15 PM',
        kind: 'transit',
        title: 'Travel to Sainte-Chapelle',
        notes: 'Short walk across Île de la Cité.',
      },
      {
        time: '3:25 PM',
        kind: 'activity',
        title: 'Sainte-Chapelle',
        notes: 'Timed entry recommended — allow 45–50 minutes for the stained glass and chapel.',
        address: '8 Boulevard du Palais, 75001 Paris',
        coords: [48.8554, 2.345],
      },
      {
        time: '4:15 PM',
        kind: 'transit',
        title: 'Travel to Notre-Dame',
        notes: 'Short walk across Île de la Cité.',
      },
      {
        time: '4:30 PM',
        kind: 'activity',
        title: 'Notre-Dame de Paris',
        notes: 'Allow time for exterior views and the interior visit — check current entry arrangements in advance.',
        address: '6 Parvis Notre-Dame, 75004 Paris',
        coords: [48.853, 2.3499],
      },
      {
        time: '5:00 PM',
        kind: 'transit',
        title: 'Travel to Île Saint-Louis',
        notes: 'Short walk across Pont Saint-Louis from Notre-Dame.',
      },
      {
        time: '5:15 PM',
        kind: 'meal',
        title: 'Berthillon',
        notes: 'Classic Paris ice cream on Île Saint-Louis — closed Mondays, so today instead of the 7th.',
        address: '29-31 Rue Saint-Louis en l’Île, 75004 Paris',
        coords: [48.8517, 2.3568],
      },
      {
        time: '5:45 PM',
        kind: 'activity',
        title: 'Île de la Cité & Seine',
        notes: 'Flexible late-afternoon block — photos, river views, souvenirs, or recovery time.',
      },
      {
        time: '6:30 PM',
        kind: 'transit',
        title: 'Travel to Dinner',
        notes: 'Choose the direction based on where the afternoon ends.',
      },
      {
        time: '7:00 PM',
        kind: 'meal',
        title: 'Final Paris Dinner',
        notes: 'Flexible reservation — choose based on where the afternoon ends.',
      },
    ],
    '2026-09-09': [
      {
        time: '10:00 AM',
        kind: 'activity',
        title: 'Check-out & Pack',
        notes: 'Allow sufficient time for luggage and the final check-out.',
      },
      {
        time: '11:00 AM',
        kind: 'activity',
        title: 'Prepare to Leave',
        notes: 'Have luggage ready and depart promptly.',
      },
      {
        time: '11:15 AM',
        kind: 'transit',
        title: 'Travel to Gare de Lyon',
        notes: 'Arrive roughly 45–50 minutes before the 12:38 PM TGV.',
      },
      {
        time: '11:50 AM',
        kind: 'activity',
        title: 'Station Buffer & Boarding',
        notes: 'Find the platform and board without rushing.',
      },
    ],
  },
};
